### ISSUE TITLE
Is there an installation tutorial?

### ISSUE THREAD

**Issue by SamueldaCostaAraujoNunes** [shivajiva101/cb-wb01#1]
Hello! Nice work on the development, the original Creality Box firmware is very weak. The idea of ​​applying octo on top of it is very good, but I was unsure about installing the firmware.

**Comment by shivajiva101** [comment]
Try this [video](https://www.youtube.com/watch?v=0y3qt8cvtKY)

You should be using my fork of the [octowrt](https://github.com/shivajiva101/OctoWrt/tree/23.05.2-137) though, not this repo. Use the manual method once you get the firmware installed.
